#!/usr/bin/env bash

PROJECT_PATH="$(dirname ${BASH_SOURCE[0]})/.."
APP_PATH="${PROJECT_PATH}/app"
CMD_PATH="${PROJECT_PATH}/cmd"
WWW_PATH="${PROJECT_PATH}/www"

DEST_PATH="${WWW_PATH}/kipiton.js"

echo "// Build date: $(date --utc '+%F %T %Z')" > $DEST_PATH &&

cat "${APP_PATH}/lib/EventEmitter.js" >> $DEST_PATH &&

cat "${APP_PATH}/model/Board.js" >> $DEST_PATH &&
cat "${APP_PATH}/model/Ship.js" >> $DEST_PATH &&
cat "${APP_PATH}/model/TimeBonus.js" >> $DEST_PATH &&
cat "${APP_PATH}/model/Game.js" >> $DEST_PATH &&

cat "${APP_PATH}/drawer/Drawer.js" >> $DEST_PATH &&
cat "${APP_PATH}/drawer/BoardDrawer.js" >> $DEST_PATH &&
cat "${APP_PATH}/drawer/ShipDrawer.js" >> $DEST_PATH &&
cat "${APP_PATH}/drawer/GameOverDrawer.js" >> $DEST_PATH &&
cat "${APP_PATH}/drawer/PauseDrawer.js" >> $DEST_PATH &&
cat "${APP_PATH}/drawer/Renderer.js" >> $DEST_PATH &&

cat "${APP_PATH}/controller/KeyboardController.js" >> $DEST_PATH &&

cat "${APP_PATH}/main.js" >> $DEST_PATH
