#!/usr/bin/env bash

PROJECT_PATH="$(dirname ${BASH_SOURCE[0]})/.."
APP_PATH="${PROJECT_PATH}/app"
WWW_PATH="${PROJECT_PATH}/www"

DEST_PATH="${WWW_PATH}/kipiton.js"

echo "// Build date: $(date --utc '+%F %T %Z')" > $DEST_PATH &&

cat "${APP_PATH}/lib/EventEmitter.js" >> $DEST_PATH &&

cat "${APP_PATH}/model/hitbox/error/UnsupportedHitboxType.js" >> $DEST_PATH &&
cat "${APP_PATH}/model/hitbox/RectHitbox.js" >> $DEST_PATH &&
cat "${APP_PATH}/model/hitbox/CircleHitbox.js" >> $DEST_PATH &&

cat "${APP_PATH}/model/DangerZone.js" >> $DEST_PATH &&
cat "${APP_PATH}/model/Ship.js" >> $DEST_PATH &&
cat "${APP_PATH}/model/TimeBonus.js" >> $DEST_PATH &&
cat "${APP_PATH}/model/Countdown.js" >> $DEST_PATH &&
cat "${APP_PATH}/model/Timer.js" >> $DEST_PATH &&
cat "${APP_PATH}/model/Game.js" >> $DEST_PATH &&

cat "${APP_PATH}/drawer/Drawer.js" >> $DEST_PATH &&
cat "${APP_PATH}/drawer/DangerZoneDrawer.js" >> $DEST_PATH &&
cat "${APP_PATH}/drawer/ShipDrawer.js" >> $DEST_PATH &&
cat "${APP_PATH}/drawer/GameOverDrawer.js" >> $DEST_PATH &&
cat "${APP_PATH}/drawer/PauseDrawer.js" >> $DEST_PATH &&
cat "${APP_PATH}/drawer/CountdownDrawer.js" >> $DEST_PATH &&
cat "${APP_PATH}/drawer/TimerDrawer.js" >> $DEST_PATH &&
cat "${APP_PATH}/drawer/TimeBonusDrawer.js" >> $DEST_PATH &&
cat "${APP_PATH}/drawer/Renderer.js" >> $DEST_PATH &&

cat "${APP_PATH}/controller/KeyboardController.js" >> $DEST_PATH &&

cat "${APP_PATH}/main.js" >> $DEST_PATH &&

cp "${APP_PATH}/html/game.html" "${WWW_PATH}/index.html"
